@AltaGasAssignment.WebApi_HostAddress = http://localhost:5257

GET {{AltaGasAssignment.WebApi_HostAddress}}/init

###

GET {{AltaGasAssignment.WebApi_HostAddress}}/trips?PageSize=7&pageNumber=1&OrderBy=ShortestTrip

###
